import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex justify-between mt-5 mx-20">
          <header>
            <h1>건호 블로그</h1>
          </header>
          <ul>
            <li className="flex gap-4">
              <Link href="/">home</Link>
              <Link href="/about">about</Link>
              <Link href="/posts">posts</Link>
              <Link href="/contact">contact</Link>
            </li>
          </ul>
        </div>
        {children}
      </body>
    </html>
  );
}
